### ISSUE TITLE
国服 稳定源 半音rank表图片存在问题无法发送

### ISSUE THREAD

**Issue by Tachibana-Kin** [pcrbot/pcr-rank_data#16]
国服 稳定源 半音 rank表的第一个png文件无法被QQ识别。文件仅能被UWP版图片打开，不能被ACDSee识别。另存转换格式扔不能解决问题
![35AV3WMNJ(K`MTYY9@}}VQ8](https://user-images.githubusercontent.com/19606268/152163315-fe42fce6-72d0-456c-894e-f4ae5efccd80.png)

伴生Hoshino<ActionFailed, retcode=100>错误疑似与其有关
![image](https://user-images.githubusercontent.com/19606268/152163576-155be638-8fc5-4375-adf7-807078e82103.png)

**Comment by rishenshun** [comment]
我这边用Windows自带画图、PS打开正常，尝试把图片稍微缩小、转换成JPG后能发，但是没过多久又风控了。

**Comment by ColdThunder11** [comment]
> 国服 稳定源 半音 rank表的第一个png文件无法被QQ识别。文件仅能被UWP版图片打开，不能被ACDSee识别。另存转换格式扔不能解决问题 ![35AV3WMNJ(K`MTYY9@}}VQ8](https://user-images.githubusercontent.com/19606268/152163315-fe42fce6-72d0-456c-894e-f4ae5efccd80.png)
> 
> 伴生Hoshino<ActionFailed, retcode=100>错误疑似与其有关 ![image](https://user-images.githubusercontent.com/19606268/152163576-155be638-8fc5-4375-adf7-807078e82103.png)

已经重新上传，请重新发送“更新rank表缓存”更新或等待今天自动更新
