### ISSUE TITLE
台服新RANK，求更新

### ISSUE THREAD

**Issue by JiangSirr** [pcrbot/pcr-rank_data#21]
![3](https://user-images.githubusercontent.com/94414806/158964826-54f2ce83-b5ca-4d1d-8490-8bbc3de9f467.png)
![2](https://user-images.githubusercontent.com/94414806/158964864-bb391629-238e-4b7f-88c3-867770beea90.png)
![1](https://user-images.githubusercontent.com/94414806/158964878-f162abae-6c05-4ef5-bb41-e1235d934d0d.png)
![4](https://user-images.githubusercontent.com/94414806/158964886-b0b391bc-3da6-44aa-bab1-11251bc6fdbc.png)

**Comment by ColdThunder11** [comment]
昨天github炸了我以为push上去了但是并没有www，已经更新了手动更新下或者等明天自动更新
