### ISSUE TITLE
申请加入花舞组rank表

### ISSUE THREAD

**Issue by Grampus2012** [pcrbot/pcr-rank_data#24]
随着花舞组作业在非前排工会中越来越流行，会员们认为在rank表中自动查询花舞组rank表很有吸引力，申请在stable中加入花舞组rank数据。制作好的文件请见链接[https://www.dropbox.com/sh/bo1u54cblasbjcb/AADJHFf6rZdk91UzzlwFcoD5a?dl=0](url)

**Comment by ColdThunder11** [comment]
~~建议右转pull requests~~

**Comment by ColdThunder11** [comment]
#25 已添加
