### ISSUE TITLE
台服R21-5

### ISSUE THREAD

**Issue by JiangSirr** [pcrbot/pcr-rank_data#7]
![kjQ8kcl-3ztqXiZ4xT3cS16d-31g](https://user-images.githubusercontent.com/94414806/141872551-fd1a01aa-2592-48af-a62e-ffdf17c38a8f.png)
![kjQ8kcl-ac9fXkZ5nT3cS16d-3js](https://user-images.githubusercontent.com/94414806/141872561-471fce6b-0e9b-4bbb-9e7b-1611e92317bc.png)
![kjQ8kcw-7divXhZ4uT3cS16d-2xs](https://user-images.githubusercontent.com/94414806/141872566-0540942e-1f30-496e-b4fb-efdd6bbff5e7.png)

**Comment by GirlKiller512** [comment]
Updated
